### ISSUE TITLE
[Refactoring] Remove 農用範圍回報限制

### ISSUE THREAD

**Issue by tai271828** [tai271828/disfactory-frontend#15]
**Describe the solution you'd like**
The current codebase allows reporting in the range of 農用範圍 only. In our case, we don't need this restriction.

**Comment by diaoga** [comment]
- GIS layer can be a tool to recognition corresponding authority i.e. 玉山國家公園, 東勢林區管理處 etc.
- Also it can serve as virtual fence function for human-bear conflict risk warning
**These are out of scope!**

**Comment by tai271828** [comment]
@joshuay1 fwiw, if you are interested in this issue, @yanghaochang104 has divided into the code of layer stack. The knowledge may help (or not).

**Comment by tai271828** [comment]
It seems @yanghaochang104 's up-coming pull request will resolve this issue.

**Comment by yanghaochang104** [comment]
done!
please take a look at #51

**Comment by tai271828** [comment]
Verified with the development site. The restriction layer is gone.
