### ISSUE TITLE
[Umbrella Issue] Change theme

### ISSUE THREAD

**Issue by tai271828** [tai271828/disfactory-frontend#2]
**Describe the solution you'd like**
We are porting our system from Disfactory. Change the theme to be more specific to the project of TBBCA.

**Comment by zztin** [comment]
At these places we can find code related to colors.
```
disfactory-frontend/src/plugins/vuetify.ts
disfactory-frontend/src/styles/variables.scss
disfactory-frontend/src/styles/pages.scss
```
grep "#" for most lines containing colors. 
Sometimes colors are pre-defined material colors. Will show as `colors.xxxx.base`
These colors are imported, and files would contain line:
`from import colors from 'vuetify/lib/util/colors'`

**Comment by tai271828** [comment]
Duplicate of https://github.com/tai271828/disfactory-frontend/issues/23 Let's use https://github.com/tai271828/disfactory-frontend/issues/23 to track this issue.
