### ISSUE TITLE
Themepage "安全須知"->

### ISSUE THREAD

**Issue by diaoga** [tai271828/disfactory-frontend#27]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by diaoga** [comment]
I don't know how to delete this mistaken issue @@

**Comment by tai271828** [comment]
You can delete an issue with the button bottom-right. If the issue is not a spam, feel free to keep it closed and this is sufficient.

![Selection_599](https://user-images.githubusercontent.com/3217432/148249811-2133fe2d-112e-4400-9014-805213b8ce1a.png)
