### ISSUE TITLE
[Featuer request] Contents of "黑熊痕跡辨識秘訣" on themepage 

### ISSUE THREAD

**Issue by diaoga** [tai271828/disfactory-frontend#28]
We should find somewhere to place "黑熊痕跡辨識秘訣" on themepage.

I thought forking "安全須知" on disfactory to "黑熊痕跡辨識秘訣" will be a good choice.

I will prepare pages of material(image and text) for that before 12/22.

**Comment by zztin** [comment]
可以將內容更新到這個文件中的安全須知section 
https://hackmd.io/-bABikFPRuOEmP3NtXNdWw?view

**Comment by zztin** [comment]
我建議黑熊痕跡辨識秘訣放在常見問題

**Comment by zztin** [comment]
updates see #37
