### ISSUE TITLE
[Umbrella Project][Refactoring] Wording of landing page

### ISSUE THREAD

**Issue by tai271828** [tai271828/disfactory-frontend#32]

**Comment by zztin** [comment]
Issue #36 #37 #18 contain details of this issue. 
There are 6 tabs on the upper right corner of the landing page. 

Currently: 4 out of 6 are tackled. 

- [ ] 使用教學
- [x] 安全須知
- [x] 聯絡我們
- [ ] 常見問題 
- [x] 關於通報系統
- [x] 問題回報 

"常見問題" --> 建議作為獨立的component 與通報表單共用。
"使用教學" --> 為使用Oh Shown!通報系統的教學，等其他部分都完成後可以擷圖製作。

More details on:
https://hackmd.io/-bABikFPRuOEmP3NtXNdWw?both

**Comment by tai271828** [comment]
Cool! Thanks for the status update. Please note 使用教學 and 常見問題 are blocked by https://github.com/tai271828/disfactory-frontend/issues/44 currently QQ

**Comment by tai271828** [comment]
Use https://github.com/tai271828/disfactory-frontend/issues/23 to track instead.
