### ISSUE TITLE
[Refactoring] Replace favicon

### ISSUE THREAD

**Issue by tai271828** [tai271828/disfactory-frontend#33]
**Describe the solution you'd like**
The favicon should be replaced to be more bear-ish.
![Selection_596](https://user-images.githubusercontent.com/3217432/148243468-032a7e8e-62c8-4ec2-b762-50f72342a444.png)

**Comment by zztin** [comment]
Hi, 
While opening: http://ohshown.site:8080 (On: 2022/1/21)

我發現在chrome favicons是 正確的熊熊沒錯，但在safari的 tab icon 還是 「拆」。這也是favicons的一部分嗎？若不是，可能可以在這個issue一起修掉？

- Chrome
<img width="352" alt="Screen Shot 2022-01-21 at 1 47 59 PM" src="https://user-images.githubusercontent.com/32836585/150529552-6c7f48a5-e28c-4324-bb87-40393f9b7294.png">

- Safari 網址列
<img width="358" alt="Screen Shot 2022-01-21 at 1 48 53 PM" src="https://user-images.githubusercontent.com/32836585/150529719-753b0fdb-4c78-40a3-918f-394231849704.png">


- Safari tab:
<img width="746" alt="Screen Shot 2022-01-21 at 1 43 52 PM" src="https://user-images.githubusercontent.com/32836585/150529289-7cae9cdb-d49d-4d96-b24e-b262b5cdbc88.png">

**Comment by zztin** [comment]
另外，想請問
ohshown.site:8080 -- 黑熊出沒痕跡通報 | Black Bears!!
後面這段文字是不是要改成`Oh Shown!` ?

(不小心關掉issue了，reopen。)

**Comment by tai271828** [comment]
可能是個問題；不過測試的時候也可能是瀏覽器沒更新到頁面。可以試著請你或誰有 safari 的夥伴，有空的時候 safari 開無痕（或類似功能）看看嗎？

> Hi, While opening: http://ohshown.site:8080 (On: 2022/1/21)
> 
> 我發現在chrome favicons是 正確的熊熊沒錯，但在safari的 tab icon 還是 「拆」。這也是favicons的一部分嗎？若不是，可能可以在這個issue一起修掉？
> 
> * Chrome : As expected 100
> 
> <img alt="Screen Shot 2022-01-21 at 1 47 59 PM" width="352" src="https://user-images.githubusercontent.com/32836585/150530152-de995bcc-e729-429a-956d-cc438784895b.png">
> 
> * Safari 網址列: As expected 100
> 
> <img alt="Screen Shot 2022-01-21 at 1 48 53 PM" width="358" src="https://user-images.githubusercontent.com/32836585/150529719-753b0fdb-4c78-40a3-918f-394231849704.png">
> 
> * Safari tab: Wrong -1
> 
> <img alt="Screen Shot 2022-01-21 at 1 43 52 PM" width="746" src="https://user-images.githubusercontent.com/32836585/150529289-7cae9cdb-d49d-4d96-b24e-b262b5cdbc88.png">
> 
> The browser version I am on: Safari: Version 14.0.3 (16610.4.3.1.4)

**Comment by tai271828** [comment]
> 另外，想請問 ohshown.site:8080 -- 黑熊出沒痕跡通報 | Black Bears!! 後面這段文字是不是要改成`Oh Shown!` instead of `Black Bears!!`

屬於「設計」類的討論，另外開 issue 追蹤 https://github.com/tai271828/disfactory-frontend/issues/42

**Comment by tai271828** [comment]
> 另外，想請問 ohshown.site:8080 -- 黑熊出沒痕跡通報 | Black Bears!! 後面這段文字是不是要改成`Oh Shown!` instead of `Black Bears!!`

感謝眼尖回報提案！這屬於設計範圍的討論，我們另外開 issue 追蹤 https://github.com/tai271828/disfactory-frontend/issues/42

**Comment by zztin** [comment]
嘗試無痕也是一樣：）
這個ohshown.site 是新的網址（第一次連），應該不是瀏覽器更新的問題？
不過也請其他夥伴有空試試看。

**Comment by diaoga** [comment]
Hi @joshuay1 
Here are vector icons 
https://drive.google.com/drive/folders/1IK0KQTlRsZ16_9hszvM9_VYyGu9eVRgz?usp=sharing

**Comment by joshuay1** [comment]
Thanks @zztin for pointing this out! I looked into it and I realised that we need a 'safari-pinned-tab.svg' for the safari tab. I will crop the vector .ai @diaoga provided and make a new .svg icon out of it. Will get it done before end of the week. Cheers.


> 我發現在chrome favicons是 正確的熊熊沒錯，但在safari的 tab icon 還是 「拆」。這也是favicons的一部分嗎？若不是，可能可以在這個issue一起修掉？
> 
> * Chrome : As expected 💯
> 
> <img alt="Screen Shot 2022-01-21 at 1 47 59 PM" width="352" src="https://user-images.githubusercontent.com/32836585/150530152-de995bcc-e729-429a-956d-cc438784895b.png">
> 
> * Safari 網址列: As expected 💯
> 
> <img alt="Screen Shot 2022-01-21 at 1 48 53 PM" width="358" src="https://user-images.githubusercontent.com/32836585/150529719-753b0fdb-4c78-40a3-918f-394231849704.png">
> 
> * Safari tab: Wrong 👎
> 
> <img alt="Screen Shot 2022-01-21 at 1 43 52 PM" width="746" src="https://user-images.githubusercontent.com/32836585/150529289-7cae9cdb-d49d-4d96-b24e-b262b5cdbc88.png">
> 
> The browser version I am on: Safari: Version 14.0.3 (16610.4.3.1.4)

**Comment by diaoga** [comment]
已確認: 上方提供的icon，只要是台灣黑熊保育協會出版/開發的產品，都可以自由運用

**Comment by zztin** [comment]
On Safari 👍  
<img width="253" alt="Screen Shot 2022-02-09 at 10 24 08 AM" src="https://user-images.githubusercontent.com/32836585/153167475-fc3511c3-b9f0-409c-9cc2-712b72c51982.png">

**Comment by tai271828** [comment]
Completed so close this issue.
