### ISSUE TITLE
[Refactoring] Landing page 關於通報系統 與 問題回報

### ISSUE THREAD

**Issue by zztin** [tai271828/disfactory-frontend#36]
**Is your feature request related to a problem? Please describe.**
目前連到disfactory的網頁
**Describe the solution you'd like**
暫時改為此repo的連結

**Comment by tai271828** [comment]
Pull request #39 has landed, but the links are not updated correspondingly. @zztin would you mind checking what's going on?

**Comment by tai271828** [comment]
The pull request https://github.com/tai271828/disfactory-frontend/pull/47 is landed. Track the "remaining" issue with https://github.com/tai271828/disfactory-frontend/pull/47
